enum QDBStatusCodes{
    SUCCESS = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NO_CONTENT = 204,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    INTERNAL_SERVER_ERROR = 500,
    SERVICE_UNAVAILABLE = 503,
}

const TABLE_NAMES_NOTALLOWED = [
    "select",
    "insert",
    "update",
    "delete",
    "create",
    "alter",
    "drop",
    "truncate",
    "rename",
    "all",
    "qdb",
    "qdb_tables",
    "qdb_columns",
    "qdb_indexes",
    "qdb_constraints",
    "qdb_triggers",
    "qdb_views",
    "qdb_functions",
    "qdb_procedures",
    "qdb_events",
    "qdb_users",
    "qdb_roles",
    "qdb_permissions",
    "qdb_sessions",
    "qdb_logs",
    "qdb_settings",
    "qdb_status",
    "qdb_config",
    "qdb_users",
    "qdb_roles",
    "qdb_permissions",
    "qdb_sessions",
    "qdb_logs",
    "qdb_settings",
    "qdb_status",
    "qdb_config"];

export { QDBStatusCodes, TABLE_NAMES_NOTALLOWED };